### ISSUE TITLE
Support for Nvidia Jetson

### ISSUE THREAD

**Issue by atahmih** [joular/powerjoular#24]
I get an error Platform not supported when running on an Nvidia Jetson Xavier. I assumed as it was an ARM architecture as Raspberry Pi, Powerjoular would work on it, but that's not the case.

**Comment by adelnoureddine** [comment]
The support we have for ARM devices is limited to select models for Raspberry Pi and Asus Tinker Board. This is because we created our own empirical power models for these devices (using our CPU benchmarking approach in the Joular project).
