### ISSUE TITLE
Question regarding Raspberry Pi power measurement

### ISSUE THREAD

**Issue by charles-typ** [joular/powerjoular#37]
Hi,

Thanks for the interesting project.

I want to use Powerjoular for another ARM SoC (not Raspberry Pi), so I'm curious how you came up with the regression model for RPi. Also, does the power measurement for RPi contain everything on board, including DRAM, or just the processor?

Thanks!

**Comment by adelnoureddine** [comment]
Hi @charles-typ, the regression models we used are based on an empirical benchmarking approach.
We measured the power consumption of the board with a power meter, while stressing the CPU at various levels (all other components were turned off or put to a minimum, so the power meter gets the power of the CPU).

If you have a power meter, you can run our benchmark and it'll generate a power model for it too.
The benchmark for Linux-based SBC is available here: [CPU Power Benchmark](https://github.com/joular/cpupowerbench).
And you can get more information about our benchmarking approach in our [research paper here](https://hal.science/hal-03912723v1/document).

**Comment by charles-typ** [comment]
Thanks a lot for the information and pointers! Closing for now.
