### ISSUE TITLE
Invalid switch causes an  unhandled exception

### ISSUE THREAD

**Issue by gcorrall** [joular/powerjoular#58]
Giving an invalid switch to powerjoular on the command line raises an unhandled exception, displaying:

`raised GNAT.COMMAND_LINE.INVALID_SWITCH : g-comlin.adb:756`

I think handling the 'Invalid_Switch' exception to show an appropriate error message (or displaying the help text) would be preferable (e.g. https://www.adacore.com/gems/gem-52).

**Comment by adelnoureddine** [comment]
Thanks @gcorrall, I'll add handling these exceptions to the code.

**Comment by adelnoureddine** [comment]
Fixed in  45c3119.

**Comment by gcorrall** [comment]
I think this change may have broken things somewhat; running powerjoular (with no switch or any valid switch) now exits immediately (whilst an invalid switch does display an error message).

**Comment by adelnoureddine** [comment]
Indeed, I just pushed a hotfix, should fix it.
