### ISSUE TITLE
Monitoring by application gives wrong values

### ISSUE THREAD

**Issue by gcorrall** [joular/powerjoular#61]
When monitoring an application by its name I think the output is wrong when there are a range of PIDs to process, If, for example, I run `powerjoular -ta firefox` the 'CPU Utilization Percentage' will permanently stay at 0.00%.

Looking at the code, I think there may be an error in `cpu_stat_app.adb`, and that only the first PID is processed; that is, in `Update_PID_Array`:

`App_Data.PID_Array(Loop_I) := Integer'Value (String_Split.Slice (Subs, 1));`

should be

`App_Data.PID_Array(Loop_I) := Integer'Value (String_Split.Slice (Subs, I)); `

**Comment by adelnoureddine** [comment]
Thanks for the report, I'll look over it and add the fix.

**Comment by adelnoureddine** [comment]
Fixed in 7ed27bf. Thanks!
